apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  config.txt: "This is a placeholder for the Prometheus configuration. In a production environment, you should replace this with a proper Prometheus configuration."