apiVersion: v1
kind: Service
metadata:
  name: lessoncraft
  labels:
    app: lessoncraft
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: lessoncraft
  type: ClusterIP